logLevel: info
wsEndpoint: "wss://rpc.polkadot.io/"
isDeepHistoryCheckForced: true
transactions:
- sender:
    alias: sender1
    keystore:
      filePath: /sender1/keystore/data.json
      passwordPath: /sender1/keystore/password.txt
  receiver:
    alias: receiver1
    address: 5DwAurocRcvfdozAuyojRwYVy9k7h8yekrrBKaDdfEhN13sJ
  restriction:
    remaining: 850000000000000 # leave this much in the sender, send the rest
- sender:
    alias: sender1
    keystore:
      filePath: /sender2/keystore/data.json
      passwordPath: /sender1/keystore/password.txt
  receiver:
    alias: receiver2
    address: 5F7dw2gF9DfGoBVdaWfv8ZLTZHrj8wQ7JeSGsPFp7yNkuNdy
  restriction:
    desired: 10000000000000 # send desired - current_receiver_balance, if current_receiver_balance >= desired noop
claims:
- alias: stash1
  controllerAddress: 5DwAurocRcvfdozAuyojRwYVy9k7h8yekrrBKaDdfEhN13sJ
  keystore:
    filePath: /stash1/keystore/data.json
    passwordPath: /stash1/keystore/password.txt
- alias: stash2
  controllerAddress: 5F7dw2gF9DfGoBVdaWfv8ZLTZHrj8wQ7JeSGsPFp7yNkuNdy
  keystore:
    filePath: /stash2/keystore/path/
    passwordPath: /stash2/keystore/password.txt
